PROGRAM READFILE
INTEGER I, UNIT	, GRADE, N,M, GRADEPOINT, NUMBER
REAL GP
CHARACTER*6 COURSE
OPEN(UNIT = 1,FILE = "TOSINSNEWFILE.TXT",ACTION = "WRITE")
OPEN(UNIT = 2, FILE = "NUMBERS.TXT", ACTION ="READ")
READ(2,*) NUMBER
20 FORMAT( "COURSE", T18, "UNIT", T38, "POINT",10X, "GRADEPOINT")
WRITE(1,20)
N = 0
M = 0

DO I = 1,9

READ(2,*) COURSE,UNIT, GRADE
GRADEPOINT =  UNIT * GRADE
N = GRADEPOINT + N
M = UNIT + M  

WRITE(1,30) COURSE, UNIT, GRADE	, GRADEPOINT
30 FORMAT(A6, T20, I1, T40, I1, T60, I3	)
END DO

GP = N/M

WRITE(1,*) "YOUR GRADEPOINT AT THE END OF THE SEMESTER IS:", N 
WRITE(1,*) "YOUR TOTAL UNIT AT THE END OF THE SEMESTER IS:", M
40 FORMAT("YOUR GP FOR THE SEMESTER IS:",10X, F4.2)
WRITE(1,40)  GP 

END PROGRAM