PROGRAM FACT
IMPLICIT NONE
INTEGER I

DO I = 1,10,1
  WRITE(*,*) I, FACTORIAL(I)
  END DO

CONTAINS
  FUNCTION FACTORIAL(N)
  INTEGER FACTORIAL, N, TEMP, I
  TEMP = 1
  DO I = 1,N
    TEMP =TEMP * I
    END DO
    FACTORIAL = TEMP
    END FUNCTION
    END PROGRAM
  
  