PROGRAM FACT
INTEGER I

DO I = 1,10
  WRITE(*,*) I, FACTORIAL(I)
  END DO

CONTAINS
  FUNCTION FACTORIAL(N)
  INTEGER FACTORIAL, N, TEMP
  DO I = 1,N
    FACTORIAL = FACTIORIAL * N
    END DO
    END FUNCTION
    END PROGRAM
  
  