!THIS PROGRAM IS GOING TO FIND THE FACTORIAL OF 1 NUMBER ONLY, TO DO THAT N NUMBERS OPEN FACT
PROGRAM FACT
INTEGER I, FACTORIAL, TEMP,N
WRITE(*,*) 'ENTER NUMBER'
READ*, N
TEMP = 1
DO I = 1, N
  TEMP = I*TEMP
  END DO
  FACTORIAL = TEMP
  PRINT*, FACTORIAL
  END PROGRAM