PROGRAM CGPACALCULATOR
CHARACTER*40 COURSECODE, FIRSTNAME, LASTNAME
INTEGER  TOTALUNIT, I, N,TOTALNUMBCOURSE, MATRICNUMBER,SCORE
REAL GPA,CGPA
INTEGER, DIMENSION(:), ALLOCATABLE:: UNIT
OPEN(UNIT=1, FILE = 'STUDENTRECORD.DAT',STATUS = 'OLD', ACTION = 'READ')
OPEN(UNIT=2, FILE = 'TRANSCRIPT.DAT')
WRITE(*,*) 'ENTER NUMBER OF COURSES'
READ*, N
ALLOCATE(UNIT(N))
!READ(1,*) FIRSTNAME, LASTNAME, MATRICNUMBER
!WRITE(2,*) 'NAME:', FIRSTNAME, LASTNAME
!WRITE(2,*) 'MATRICNUMBER', MATRICNUMBER
20 FORMAT('COURSECODE', T20, 'UNIT', T40,'SCORE', T60,'POINT',T80, 'AVERAGE')
WRITE(2,20)

AVERAGE = 0
DO I = 1, N
READ(1,*) COURSECODE, UNIT, SCORE
SELECT CASE(SCORE)
  CASE(70:)
   POINT = 7
   AVERAGE = 7*UNIT(I)
  CASE(65:69)
   POINT = 6
   AVERAGE = 6*UNIT(I)
  CASE(60:64)
   POINT = 5
   AVERAGE = 5*UNIT(I)
  CASE(55:59)
   POINT = 4
   AVERAGE = 4*UNIT(I)
  CASE(50:54)
   POINT = 3
   AVERAGE = 3*UNIT(I)
  CASE(45:49)
   POINT = 2
   AVERAGE = 2*UNIT(I)
  CASE(40:44)
   POINT = 1
   AVERAGE = 1*UNIT(I)
  CASE(:39)
   POINT = 0
   AVERAGE = O
   END SELECT 
WRITE(2,*) COURSECODE, UNIT(I), SCORE, POINT, AVERAGE

AVERAGE = AVERAGE + AVERAGE
END DO

TOTALUNIT = SUM(UNIT)   
GPA = AVERAGE / TOTALUNIT
WRITE(*,*) 'YOUR GPA THIS SEMESTER IS ', GPA

DEALLOCATE(UNIT)
END PROGRAM