 PROGRAM CGPACALCULATOR
CHARACTER*20 COURSECODE, FIRSTNAME, LASTNAME
INTEGER   I, N, TOTALNUMBCOURSE, MATRICNUMBER, SCORE,POINT , IO
INTEGER, PARAMETER::MAX=20 
REAL GPA,CGPA,TOTALSUM,TOTALUNIT
CHARACTER*10, DIMENSION(MAX):: X
REAL, DIMENSION(:), ALLOCATABLE:: UNIT,AVERAGE
OPEN(UNIT=1, FILE = 'STUDENTRECORD.DAT',STATUS = 'OLD', ACTION = 'READ')
OPEN(UNIT=2, FILE = 'TRANSCRIPT.DAT')
!WRITE(*,*) 'ENTER NUMBER OF COURSES'
READ(1,*) N

ALLOCATE(UNIT(N))
ALLOCATE(AVERAGE(N))
READ(1,*) FIRSTNAME, LASTNAME, MATRICNUMBER
WRITE(2,21)  FIRSTNAME, LASTNAME
21 FORMAT('NAME:',2X,A8, 2X, A20)
WRITE(2,23)  MATRICNUMBER
23 FORMAT('MATRICNUMBER:', 5X, I6)
20 FORMAT('COURSECODE', T20, 'UNIT', T30,'SCORE', T40,'POINT',T50, 'GRADE POINT')
WRITE(2,20)

!AVERAGE = 0
DO I = 1, N
READ(1,*) COURSECODE, UNIT(I), SCORE
SELECT CASE(SCORE)
  CASE(70:)
   POINT = 7
   AVERAGE(I) = 7*UNIT(I)
  CASE(65:69)
   POINT = 6
   AVERAGE(I) = 6*UNIT(I)
  CASE(60:64)
   POINT = 5
   AVERAGE(I) = 5*UNIT(I)
  CASE(55:59)
   POINT = 4
   AVERAGE(I) = 4*UNIT(I)
  CASE(50:54)
   POINT = 3
   AVERAGE(I) = 3*UNIT(I)
  CASE(45:49)
   POINT = 2
   AVERAGE(I) = 2*UNIT(I)
  CASE(40:44)
   POINT = 1
   AVERAGE(I) = 1*UNIT(I)
   
  CASE(:39)
   POINT = 0
   AVERAGE(I) = O
   END SELECT
    
WRITE(2,22) COURSECODE, UNIT(I), SCORE, POINT, AVERAGE(I)
22 FORMAT(A6, T20 ,F5.2,T30,I2,T40,I2,T55,F5.2)

END DO

TOTALUNIT = SUM(UNIT)   
TOTALSUM= SUM(AVERAGE) 
GPA = TOTALSUM/TOTALUNIT
WRITE(2,*)  'YOUR GPA THIS SEMESTER IS ',GPA
WRITE(2,*) 'YOUR WEIGHTED GRADE POINT', TOTALSUM
WRITE(2,*) 'YOUR TOTAL UNIT TILL DATE', TOTALUNIT

DEALLOCATE(UNIT)
DEALLOCATE(AVERAGE)
END PROGRAM						