PROGRAM TOPCLASS
CHARACTER*40 TOPNAME, NAME
INTEGER SCORE, TOPMARK
OPEN(UNIT = 1, FILE = 'INPUT.TXT')
TOPMARK = 0

DO I =1,21
  READ(1,*) NAME, SCORE
  IF(SCORE>TOPMARK)THEN
    TOPMARK = SCORE
    TOPNAME = NAME
   END IF
   END DO
WRITE(*,*) TOPNAME, TOPMARK
END PROGRAM 